# Generated by Django 2.1 on 2019-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'POS-User'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='Email',
        ),
        migrations.AddField(
            model_name='users',
            name='Emailaddress',
            field=models.EmailField(default='info@treadstoneconsult.com', max_length=254),
        ),
    ]
